version: '3'

services:
  flask-pytest-mock:
    build: .
    container_name: api
    ports:
      - "6000:5000"
    volumes:
      - .:/app/api
    depends_on:
      - db
    networks:
      - flask-pytest-mock

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
    volumes:
      - './mysql-data:/var/lib/mysql'
    networks:
      - flask-pytest-mock

networks:
  flask-pytest-mock:
    name: flask-pytest-mock